local Loader = dofile("local-tests/harness/load-addon.lua")
local Test = dofile("local-tests/harness/test.lua")

local addon = Loader.LoadMetadata({ fixture = true })
local metadata = addon.RecipeMetadata

Test.it("normalizes negative spell keys", function()
    local normalized = metadata:NormalizeRecipeKey(-28596)
    Test.eq(normalized.recipeKey, -28596)
    Test.eq(normalized.source, "spell")
    Test.eq(normalized.spellId, 28596)
    Test.eq(normalized.recipeItemId, 22900)
    Test.eq(normalized.createdItemId, 22845)
end)

Test.it("normalizes positive recipe-item keys before created-item keys", function()
    local normalized = metadata:NormalizeRecipeKey(22900)
    Test.eq(normalized.source, "recipeItem")
    Test.eq(normalized.spellId, 28596)
    Test.eq(normalized.recipeItemId, 22900)
    Test.eq(normalized.createdItemId, 22845)
end)

Test.it("normalizes unique positive created-item keys", function()
    local normalized = metadata:NormalizeRecipeKey(22845)
    Test.eq(normalized.source, "createdItem")
    Test.eq(normalized.spellId, 28596)
    Test.eq(normalized.recipeItemId, 22900)
    Test.eq(normalized.createdItemId, 22845)
end)

Test.it("preserves ambiguous created-item mappings", function()
    local normalized = metadata:NormalizeRecipeKey(21840)
    Test.eq(normalized.source, "createdItem")
    Test.eq(normalized.createdItemId, 21840)
    Test.eq(normalized.spellId, nil)
    Test.eq(#normalized.ambiguousSpellIds, 2)
    Test.eq(normalized.ambiguousSpellIds[1], 26745)
    Test.eq(normalized.ambiguousSpellIds[2], 26746)
    Test.eq(metadata:GetRecipeInfo(21840), nil)
    Test.eq(metadata:GetMetadataResolutionStatus(21840), "ambiguous")
end)

Test.it("classifies invalid and unknown keys conservatively", function()
    local invalid = metadata:NormalizeRecipeKey(0)
    Test.eq(invalid.source, "invalidItem")
    Test.eq(invalid.spellId, nil)

    local unknown = metadata:NormalizeRecipeKey(999999)
    Test.eq(unknown.source, "unknown")
    Test.eq(unknown.spellId, nil)
    Test.eq(metadata:GetMetadataResolutionStatus(999999), "unresolved")
end)

Test.it("accepts numeric string keys without changing source semantics", function()
    Test.eq(metadata:NormalizeRecipeKey("-28596").source, "spell")
    Test.eq(metadata:NormalizeRecipeKey("22900").source, "recipeItem")
end)
