-- Generated by tools/recipe-metadata/generate_recipe_metadata.py. Do not hand-edit.
RecipeRegistryRecipeMetadata = {
    schemaVersion = 1,
    metadataVersion = "2026.05.23.2",
    flavor = "tbc",

    recipesBySpellId = {
        [2329] = {
            profession = "alchemy",
            expansion = "vanilla",
            createdItemId = 2454,
            category = "potions",
            subcategory = "combat",
            sortOrder = 20,
            requiredSkill = 1,
            bopOutput = false,
            reagents = {
                { itemId = 765, count = 1 },
                { itemId = 2449, count = 1 },
            },
        },
        [2330] = {
            profession = "alchemy",
            expansion = "vanilla",
            createdItemId = 118,
            category = "potions",
            subcategory = "healing",
            sortOrder = 30,
            requiredSkill = 1,
            bopOutput = false,
            reagents = {
                { itemId = 765, count = 1 },
                { itemId = 2447, count = 1 },
            },
        },
        [2538] = {
            profession = "cooking",
            expansion = "vanilla",
            createdItemId = 2679,
            category = "food",
            subcategory = "meat",
            sortOrder = 10,
            requiredSkill = 1,
            bopOutput = false,
            reagents = {
                { itemId = 2672, count = 1 },
            },
        },
        [2660] = {
            profession = "blacksmithing",
            expansion = "vanilla",
            createdItemId = 2862,
            category = "stones",
            subcategory = "sharpening",
            sortOrder = 10,
            requiredSkill = 1,
            bopOutput = false,
            reagents = {
                { itemId = 2835, count = 1 },
            },
        },
        [3308] = {
            profession = "mining",
            expansion = "vanilla",
            createdItemId = 3577,
            category = "metals",
            sortOrder = 60,
            bopOutput = false,
            reagents = {
                { itemId = 2776, count = 1 },
            },
        },
        [3918] = {
            profession = "engineering",
            expansion = "vanilla",
            createdItemId = 4357,
            category = "explosives",
            subcategory = "powders",
            sortOrder = 10,
            requiredSkill = 1,
            bopOutput = false,
            reagents = {
                { itemId = 2835, count = 1 },
            },
        },
        [11479] = {
            profession = "alchemy",
            expansion = "vanilla",
            recipeItemId = 9304,
            createdItemId = 3577,
            category = "transmutes",
            subcategory = "metal",
            sortOrder = 10,
            requiredSkill = 225,
            bopOutput = false,
            reagents = {
                { itemId = 3575, count = 1 },
            },
        },
        [25255] = {
            profession = "jewelcrafting",
            expansion = "tbc",
            createdItemId = 20816,
            category = "components",
            subcategory = "wire",
            sortOrder = 10,
            requiredSkill = 1,
            bopOutput = false,
            reagents = {
                { itemId = 2840, count = 2 },
            },
        },
        [26745] = {
            profession = "tailoring",
            expansion = "tbc",
            createdItemId = 21840,
            category = "cloth",
            subcategory = "bolts",
            sortOrder = 20,
            requiredSkill = 325,
            bopOutput = false,
            reagents = {
                { itemId = 21877, count = 5 },
            },
        },
        [26746] = {
            profession = "tailoring",
            expansion = "tbc",
            createdItemId = 21840,
            category = "cloth",
            subcategory = "bolts",
            sortOrder = 20,
            requiredSkill = 325,
            bopOutput = false,
            reagents = {
                { itemId = 14341, count = 1 },
                { itemId = 21840, count = 1 },
            },
        },
        [27924] = {
            profession = "enchanting",
            expansion = "tbc",
            category = "ring_enchants",
            subcategory = "self_only",
            sortOrder = 100,
            requiredSkill = 360,
            selfOnlyOutputless = true,
            reagents = {
                { itemId = 22445, count = 8 },
                { itemId = 22449, count = 10 },
            },
        },
        [28543] = {
            profession = "alchemy",
            expansion = "tbc",
            recipeItemId = 22907,
            createdItemId = 22823,
            category = "potions",
            subcategory = "mana",
            sortOrder = 110,
            requiredSkill = 305,
            bopOutput = false,
            reagents = {
                { itemId = 22785, count = 2 },
                { itemId = 22787, count = 1 },
            },
        },
        [28596] = {
            profession = "alchemy",
            expansion = "tbc",
            recipeItemId = 22900,
            createdItemId = 22845,
            category = "flasks",
            subcategory = "guardian_elixirs",
            sortOrder = 120,
            requiredSkill = 300,
            bopOutput = false,
            reagents = {
                { itemId = 22790, count = 7 },
                { itemId = 22791, count = 3 },
            },
        },
        [29669] = {
            profession = "blacksmithing",
            expansion = "tbc",
            recipeItemId = 23590,
            createdItemId = 23537,
            category = "armor",
            subcategory = "plate",
            sortOrder = 120,
            requiredSkill = 365,
            bopOutput = false,
            reagents = {
                { itemId = 23448, count = 6 },
                { itemId = 23573, count = 1 },
            },
        },
        [30303] = {
            profession = "engineering",
            expansion = "tbc",
            recipeItemId = 23799,
            createdItemId = 23761,
            category = "devices",
            subcategory = "weapons",
            sortOrder = 120,
            requiredSkill = 350,
            bopOutput = false,
            reagents = {
                { itemId = 23446, count = 4 },
                { itemId = 23783, count = 2 },
            },
        },
        [35530] = {
            profession = "leatherworking",
            expansion = "tbc",
            recipeItemId = 29664,
            createdItemId = 29540,
            category = "armor",
            subcategory = "bop",
            sortOrder = 160,
            requiredSkill = 375,
            bopOutput = true,
            reagents = {
                { itemId = 22452, count = 4 },
                { itemId = 23793, count = 6 },
            },
        },
    },

    recipeItemToSpellId = {
        [9304] = 11479,
        [22907] = 28543,
        [22900] = 28596,
        [23590] = 29669,
        [23799] = 30303,
        [29664] = 35530,
    },

    createdItemToSpellIds = {
        [118] = { 2330 },
        [3577] = { 3308, 11479 },
        [2454] = { 2329 },
        [2679] = { 2538 },
        [2862] = { 2660 },
        [4357] = { 3918 },
        [20816] = { 25255 },
        [21840] = { 26745, 26746 },
        [22823] = { 28543 },
        [22845] = { 28596 },
        [23537] = { 29669 },
        [23761] = { 30303 },
        [29540] = { 35530 },
    },

    categoriesByProfession = {
        alchemy = 
        {
            { key = "potions", label = "Potions", order = 10 },
            { key = "flasks", label = "Flasks", order = 20 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
        blacksmithing = 
        {
            { key = "stones", label = "Stones", order = 10 },
            { key = "armor", label = "Armor", order = 20 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
        cooking = 
        {
            { key = "food", label = "Food", order = 10 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
        enchanting = 
        {
            { key = "ring_enchants", label = "Ring Enchants", order = 40 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
        engineering = 
        {
            { key = "explosives", label = "Explosives", order = 10 },
            { key = "devices", label = "Devices", order = 20 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
        jewelcrafting = 
        {
            { key = "components", label = "Components", order = 10 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
        leatherworking = 
        {
            { key = "armor", label = "Armor", order = 10 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
        tailoring = 
        {
            { key = "cloth", label = "Cloth", order = 10 },
            { key = "misc", label = "Miscellaneous", order = 999 },
        },
    },

    subcategoriesByProfession = {
        alchemy = {
            flasks = 
            {
                { key = "guardian_elixirs", label = "Guardian Elixirs", order = 10 },
            },
            potions = 
            {
                { key = "combat", label = "Combat", order = 10 },
                { key = "healing", label = "Healing", order = 20 },
                { key = "mana", label = "Mana", order = 30 },
            },
        },
        blacksmithing = {
            armor = 
            {
                { key = "plate", label = "Plate", order = 10 },
            },
            stones = 
            {
                { key = "sharpening", label = "Sharpening", order = 10 },
            },
        },
        cooking = {
            food = 
            {
                { key = "meat", label = "Meat", order = 10 },
            },
        },
        enchanting = {
            ring_enchants = 
            {
                { key = "self_only", label = "Self Only", order = 10 },
            },
        },
        engineering = {
            devices = 
            {
                { key = "weapons", label = "Weapons", order = 10 },
            },
            explosives = 
            {
                { key = "powders", label = "Powders", order = 10 },
            },
        },
        jewelcrafting = {
            components = 
            {
                { key = "wire", label = "Wire", order = 10 },
            },
        },
        leatherworking = {
            armor = 
            {
                { key = "bop", label = "Bind on Pickup", order = 30 },
            },
        },
        tailoring = {
            cloth = 
            {
                { key = "bolts", label = "Bolts", order = 10 },
            },
        },
    },
}
