-- Placeholder. The real file is generated by ../WowForeverMining and dropped in
-- here, exactly as the TBC one is: same shape, flavor "forever".
--
-- It is empty rather than absent because the TOC loads it and the addon expects
-- the global to exist. An empty recipesBySpellId is a supported state: the
-- catalog falls back to what the scan itself reports, which is the only honest
-- answer before the dataset for this client exists.
--
-- Do not copy the TBC dataset in here to fill the gap. Forever is built on
-- vanilla content with recipes added and recipes changed, so TBC rows would be
-- wrong about reagents and outputs while looking authoritative.
RecipeRegistryRecipeMetadata = {
    schemaVersion = 1,
    metadataVersion = "forever-pending",
    flavor = "forever",

    recipesBySpellId = {},
}
